import SidebarProvider from "@/context/SidebarContext";
import "./globals.css";

// products provider
import ProductProvider from "@/context/ProductsContext";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import CartContext from "@/context/CartContext";
import Footer from "@/components/Footer";
import AuthenticationProvider from "@/context/AuthenticationContext";
// sidebar provider

export const metadata = {
  title: "e-dokan",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1.0",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthenticationProvider>
          <SidebarProvider>
            <CartContext>
              <ProductProvider>{children}</ProductProvider>
            </CartContext>
          </SidebarProvider>
        </AuthenticationProvider>
      </body>
    </html>
  );
}
