
import SidebarProvider from "@/context/SidebarContext";
import "./globals.css";

// products provider
import ProductProvider from "@/context/ProductsContext";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import CartContext from "@/context/CartContext";
import Footer from "@/components/Footer";
// sidebar provider

export const metadata = {
  title: "e-dokan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider>
          <CartContext>
            <ProductProvider>
              {children}
            </ProductProvider>
          </CartContext>
        </SidebarProvider>
      </body>
    </html>
  );
}
